Update Japanese translations
Sileo/Sileo pull request #101
Opened 2021-03-19 00:05 UTC by eve0415

Fix and update Japanese translations.

2021-03-19 07:33 UTC, CharlieWhile13 commented
Could you change the branch you're merging into to amy?

2021-03-19 10:28 UTC, eve0415 commented
> Could you change the branch you're merging into to amy?

Done

2021-03-20 11:02 UTC, sohsatoh requested changes
Reviewed (except for stringsdict)

2021-03-20 11:02 UTC, sohsatoh commented on Sileo/Sileo/ja.lproj/Localizable.strings
> +"Auto_Complete_Queue" = "キューをオートコンプリート";
This is a switch, so it should be "自動完了キュー" or "オートコンプリートキュー"

2021-03-20 11:07 UTC, sohsatoh requested changes
About stringsdict, you need to make the following changes.

- "クリップボードで見つかった %#@urls@ を追加しますか" to "クリップボードから %#@urls@ を追加しますか"
- "No Packages" to "パッケージ無し"

2021-03-21 15:41 UTC, eve0415 commented
Applied all suggestions.

2021-03-21 15:46 UTC, sohsatoh commented
@eve0415 i will check after the graduation ceremony. (by the way, we gonna the same university. you know?)

2021-03-21 15:57 UTC, eve0415 commented
Yeah, I've realized that a while ago; Congrat on your graduation

2021-03-21 16:01 UTC, sohsatoh commented
@eve0415 Thanks, good luck with your studies and enjoy your uni life!

2021-03-21 16:02 UTC, CharlieWhile13 commented
You now have the award for the most wholesome pull request on Sileo

2021-03-24 14:54 UTC, sohsatoh approved these changes

2021-03-27 00:02 UTC, merged