Add Norwegian Nynorsk localizations to Sileo
Sileo/Sileo pull request #109
Opened 2021-03-22 16:23 UTC by worldlydev

The Norwegian language has 2 written standards. Bokmål which I PRed in #93 and Nynorsk.

2021-03-28 05:36 UTC, coolstar requested changes

2021-03-28 05:36 UTC, coolstar commented on Sileo/AppDelegate.swift
> +            appVer += "-unc0ver"
No

2021-03-28 05:37 UTC, NotZoeyDev commented on Sileo/AppDelegate.swift
> +            appVer += "-unc0ver"
![thishowitis](https://user-images.githubusercontent.com/39314831/112743526-182d7300-8f66-11eb-8e89-a6018d1900a7.png)

2021-03-28 05:38 UTC, coolstar commented on Sileo/AppDelegate.swift
> +            appVer += "-unc0ver"
![:xqcdesk:](https://i.imgur.com/YIq34mw.gif)

2021-04-01 01:49 UTC, Diatrus commented
Use the crowdin

2021-04-01 01:49 UTC, closed without merging