Refactor DepictionMarkdownView to use WKWebView
Sileo/Sileo pull request #158
Opened 2021-06-18 06:41 UTC by kirb

This merges DepictionMarkdownView{Slow,Fast} back into a combined DepictionMarkdownView class, which hosts a WKWebView.

WKWebView is far better suited to the type of content DepictionMarkdownView handles, as compared to the current NSAttributedString HTML parser, which fires up a [slow, unstable](https://twitter.com/ddkilzer/status/1403162821035130884) legacy WebKit1 WebView in-process to rip the guts of the HTML out into the attributed string. (The new API mentioned in that linked tweet was tested initially but was really not much of an improvement.) It also works asynchronously, has significantly fewer rendering bugs, supports text selection, and has superb VoiceOver support. This implementation also improves upon the original implementation of theme switching, by simply executing some JavaScript to toggle some CSS variables, rather than fully reloading the web view contents.

The web view is implemented such that it is safe for Sileo to rely on; it can’t be made to do anything undesirable:

* Strict Content-Security-Policy (set via iOS 10.3+ [private API](https://github.com/WebKit/WebKit/blob/21cca866ece4d94dabf01c11f2586ed33aab1996/Source/WebKit/UIProcess/API/Cocoa/WKWebViewConfigurationPrivate.h#L111)) so the web view contents can’t execute JavaScript, load external resources, or attempt to break out of the restricted environment.
* Data used by the web view is stored in memory only, in a per-web view data store. Avoids any potential privacy risks, and there isn’t really anything that can be cached/stored anyway due to subresources and JS being blocked.
* Navigation will open Safari view controller or a matching universal link app. Context menu is supported on links.

I’ve tested a random selection of default repos’ depictions with this, and they seem fine. Of course I can confirm Chariz’s are working as intended. Further testing is still needed, and @Diatrus has mentioned testing performance.

As a proof-of-concept of how this can enable richer content, currently Chariz returns a richer footer view if it detects a `Sileo/2.2` user agent. Note you will need to bump the bundle version to 2.2 first. This is just for the purposes of a PoC and can be changed depending how release plans go.

It seems there should be no concerns with rendering issues, but StoreVersion should also probably be incremented for this, just to be on the safe side.

2021-06-18 13:09 UTC, kirb commented
Rebased against 2.1.x branch (fixed merge conflict in AppDelegate.swift) and deleted obsolete CSTextView/CSTextRenderView classes

2021-06-18 15:50 UTC, elihwyma approved these changes

2021-06-19 02:20 UTC, coolstar commented
Would probably also need a PR to accompany this to switch Depiction* and Featured* views to autolayout to resolve performance issues, but otherwise should be good for iOS 14+. Not too sure about 13 and lower, but will need to check

2021-06-19 02:52 UTC, kirb commented
Yep as discussed this seems to make an existing issue become really obvious - the current layout system just isn’t efficient. This problem always existed but was being obscured by the previous DepictionMarkdownView implementations being synchronous; the height was known by the first layout pass and would never change. The web view being async means it has no height until the page has loaded a few ms later, meaning the expensive {Depiction,Featured}*View layout logic fires a few times per DepictionMarkdownView, which adds up to totally destroy performance when there are more than a dozen or so views in the native depiction.

So will need to investigate refactoring every view to use auto layout before this is viable to merge. Ideally, a specific test case of a native depiction we found that totally annihilated performance (with 155 markdown views!) should be able to load on an iPhone 5s without feeling slow whatsoever.

It’s also likely that lazy loading views could help when the native depiction is complex enough that it fills up more than two screenfuls of content - and of course also for tabs that haven’t been selected yet.

2021-06-20 19:45 UTC, coolstar requested changes
Blocked on issue #159

2021-08-02 10:17 UTC, elihwyma commented
Closing for now due to this being migrated to [DepictionKit](https://github.com/RepositoryStandards/DepictionKit)

2021-08-02 10:17 UTC, closed without merging