Add Arabic localizations to Sileo
Sileo/Sileo pull request #94
Opened 2021-03-17 22:15 UTC by worldlydev

Original PR #20. Closed due to rebasing. Credit to @iA7myd

2021-03-17 22:16 UTC, worldlydev commented
Needs verification of proper RTL language support as mentioned in #33

2021-03-17 22:24 UTC, CharlieWhile13 commented
Let me get these verified with some other people, and I'll look into support/merging 👍

2021-03-17 22:34 UTC, worldlydev commented
> Let me get these verified with some other people, and I'll look into support/merging 👍

Definitely missing strings. I'm adding them in now and reformatting to match base. Shouldn't take more than a couple minutes.

Somebody else will have to translate the newly added strings though.

2021-03-17 22:35 UTC, CharlieWhile13 commented
Sure. I'll get that sorted too

2021-03-17 22:41 UTC, yazanoo16 requested changes
the first string could say "بدون فئة"
the third string could say "السمات"
and the tenth string could say "دعم المحطّة الطرفية"

everything else seems to be good so far

2021-03-17 22:53 UTC, worldlydev commented
> everything else seems to be good so far

Please be more specific than first, second, and third string. I'm not an Arabic speaker so I'm not sure which strings you are referring to.

2021-03-17 22:57 UTC, worldlydev commented
**STRINGS TO LOOK AT/NEED TRANSLATING**

_In Localizable.strings_

_Possibly correct:_
"__LocalizationCredit.Title" = "ترجمه إلى العربية iA7myd.";

_Need translating:_
"Theme" = "Theme";
"Tint_Color" = "Tint Color";
"Reset_Tint_Color" = "Reset Tint Color";
"Auto_Complete_Queue" = "Auto Complete Queue";
"Enable_Analytics" = "Enable Analytics";

"Sileo_Light" = "Sileo Light";
"Sileo_Dark" = "Sileo Dark";
"Sileo_Adaptive" = "Sileo Adaptive";
"System" = "System";

"View_Depiction" = "View Depiction";

2021-03-17 22:59 UTC, worldlydev commented
All strings are added and structured the same as base.lproj 

Just needs a little translation input and it should be ready to go :)

2021-03-17 23:07 UTC, yazanoo16 requested changes

2021-03-17 23:07 UTC, yazanoo16 commented on Sileo/Sileo/ar.lproj/Errors.strings
> +"Download_Hash_Mismatch" = "التجزئة المتوقعة %@، تم الحصول على %@ بدلًا من ذلك.";
this one could also say

"Download_Hash_Mismatch" = "التجزئة المتوقعة هي %@، لكن تم الحصول على %@ بدلًا من ذلك.";
“

2021-03-17 23:09 UTC, yazanoo16 commented
> > everything else seems to be good so far
> 
> Please be more specific than first, second, and third string. I'm not an Arabic speaker so I'm not sure which strings you are referring to.

i was basically referring to String 1, String 3 and String 10

2021-03-17 23:27 UTC, worldlydev commented on Sileo/Sileo/ar.lproj/Errors.strings
> +"No_Package.Body" = "إذا كان جديدًا، فانتظر حتى ينتهي Sileo من التحديث، ثم حاول مرة أخرى. تحقق عبر الإنترنت للمزيد من المساعدة.";
Fixed

2021-03-17 23:29 UTC, worldlydev commented on Sileo/Sileo/ar.lproj/Errors.strings
> +"Download_Size_Mismatch" = "الحجم المتوقع %@، تم الحصول على %@ بدلًا من ذلك.";
Fixed

2021-03-17 23:32 UTC, worldlydev commented on Sileo/Sileo/ar.lproj/Errors.strings
> +"Download_Hash_Mismatch" = "التجزئة المتوقعة %@، تم الحصول على %@ بدلًا من ذلك.";
Fixed

2021-03-18 03:44 UTC, iA7myd approved these changes

2021-03-18 04:15 UTC, iA7myd commented
"Theme" = "السمة";
"Tint_Color" = "لون الصبغة";
"Reset_Tint_Color" = "إعادة تعيين لون الصبغة";
"Auto_Complete_Queue" = "إكمال تلقائي لقائمة الانتظار";
"Enable_Analytics" = "تفعيل الإحصائيات";

"Sileo_Light" = "Sileo فاتح";
"Sileo_Dark" = "Sileo داكن";
"Sileo_Adaptive" = "تكيُّف Sileo";
"System" = "النظام";

"View_Depiction" = "عرض الوصف";

2021-03-18 04:17 UTC, iA7myd approved these changes

2021-03-18 07:33 UTC, worldlydev commented
> "Theme" = "السمة";
> "Tint_Color" = "لون الصبغة";
> "Reset_Tint_Color" = "إعادة تعيين لون الصبغة";
> "Auto_Complete_Queue" = "إكمال تلقائي لقائمة الانتظار";
> "Enable_Analytics" = "تفعيل الإحصائيات";
> 
> "Sileo_Light" = "Sileo فاتح";
> "Sileo_Dark" = "Sileo داكن";
> "Sileo_Adaptive" = "تكيُّف Sileo";
> "System" = "النظام";
> 
> "View_Depiction" = "عرض الوصف";

Implemented in https://github.com/Sileo/Sileo/pull/94/commits/5382ebcfd02f1a48d8330b0a356d6cb8337d0f10

2021-03-18 08:10 UTC, CharlieWhile13 commented
If no new changes are suggested I will merge later today

2021-03-18 10:56 UTC, yazanoo16 requested changes

2021-03-18 10:56 UTC, yazanoo16 commented on Sileo/Sileo/ar.lproj/Localizable.strings
> +"Package_Get_Action" = "جلب";
this one could be:
"Package_Get_Action" = "الحصول";

2021-03-18 10:56 UTC, yazanoo16 commented on Sileo/Sileo/ar.lproj/Localizable.strings
> +"Package_Hold_Enable_Action" = "تجاهل التحديثات المستقبيلة";
this one should be:
"Package_Hold_Enable_Action" = "تجاهل التحديثات المستقبلية";

2021-03-18 11:00 UTC, worldlydev commented on Sileo/Sileo/ar.lproj/Localizable.strings
> +"Package_Get_Action" = "جلب";
Fixed

2021-03-18 11:00 UTC, worldlydev commented on Sileo/Sileo/ar.lproj/Localizable.strings
> +"Package_Hold_Enable_Action" = "تجاهل التحديثات المستقبيلة";
Fixed

2021-03-18 11:17 UTC, iA7myd commented
No, please keep "Package_Get_Action" = "جلب";
It is the most correct and as translated by Apple

2021-03-18 11:24 UTC, worldlydev commented
> No, please keep "Package_Get_Action" = "جلب";
> It is the most correct and as translated by Apple

Reimplemented

2021-03-18 11:37 UTC, iA7myd commented
Ok, I think you can go ahead now @CharlieWhile13 
Thanks @worldlydev & @yazanoo16 🌹

2021-03-18 12:23 UTC, yazanoo16 commented
> No, please keep "Package_Get_Action" = "جلب";
> It is the most correct and as translated by Apple

oh understandable

2021-03-18 12:24 UTC, yazanoo16 commented
> Ok, I think you can go ahead now @CharlieWhile13
> Thanks @worldlydev & @yazanoo16 🌹

you’re always welcome! i’m so glad for helping here :)

2021-03-18 17:28 UTC, merged